### ISSUE TITLE
Where to discover the endpoint?

### ISSUE THREAD

**Issue by OR13** [peppelinux/draft-demarco-oauth-nonce-endpoint#9]
Should there be guidance on where the endpoint can be discovered?

Including but not limited to:

- `.well-known/jwt-vc-issuer`
- `.well-known/openid-configuration`

...

**Comment by peppelinux** [comment]
this is protocol agnostic, it could be for oauth AS or client openid rp or op and so on

I agree that we have to create a `Metadata` section where the `nonce_endpoint` will be defined and an IANA registration for that

**Comment by peppelinux** [comment]
A Pull Request is required where the metadata parameter is explained (and defined, for IANA registration)

**Comment by peppelinux** [comment]
See https://github.com/peppelinux/draft-demarco-nonce-endpoint/pull/16

**Comment by peppelinux** [comment]
Closed by https://github.com/peppelinux/draft-demarco-oauth-nonce-endpoint/pull/16
